version: "3"
services:
  idp_harness_platform:
    build:
      context: ../contrib/docker
      dockerfile: devcontainer.Dockerfile
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    container_name: idp_harness_platform
