apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: crisdemo
  description: kubernetes cluster
  links:
    - url: http://crisdemo.s3-website.us-east-1.amazonaws.com
      title: crisdemo
      icon: dashboard
      type: s3-bucket
  annotations:
    harness.io/workspace-url: |
      terraformawss3staticwebsitedev: https://app.harness.io/ng/account/Io9SR1H7TtGBq9LVyJVB2w/module/iacm/orgs/genterademo/projects/iac/workspaces/terraformawss3staticwebsitedev/resources
spec:
  type: s3-bucket
  owner: cristian.ramirez@harness.io
  system: gentera-demo-iac
